# Generated by Django 4.1.3 on 2023-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaffee', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
    ]
